# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tense_check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='test_res',
            new_name='test_res_pass',
        ),
        migrations.AddField(
            model_name='sentence',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sentence',
            name='test_res_fail',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
