# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tense_check', '0002_auto_20171104_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='comment',
        ),
    ]
